name: Run bash script tests for retrieving package name

env:
  owner: ${{ github.repository_owner }} 
  token: ${{ secrets.TOKEN }}
  pathToFolder: repository-package-nameg
  expectedPackageName: com.test-package.using-java-maven

on:
  push:

jobs:
  run-tests:
    name: "Run bash script file with tests"
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install the shunit2 on the github runner
        run: sudo apt-get update && sudo apt-get install -y shunit2

      - name: Run the test folder with the shunit2 framework
        run: ./tests/test.sh $pathToFolder $owner $token $expectedPackageName