name: Run bash script tests for retrieving package name

env:
  owner: ${{ secrets.OWNER }} 
  token: ${{ secrets.TOKEN }}
  expectedPackageName: com.test-package.using-java-maven
  pathToFolder: .

on:
  schedule:
    - cron: '* 11 * * *' # Runs only on Monday at 11:00 AM

  pull_request:
    branches:
      - master
    types: 
      - opened
      - synchronize

jobs:
  run-tests:
    if: github.event.pull_request.merged == true
    name: "Run bash script file with tests"
    strategy:
      matrix:
        envOS: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.envOS }}
    steps:  
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install the shunit2 for UNIX environment
        if: ${{ matrix.envOS == 'macos-latest' }}
        run: brew install shunit2

      - name: Install the shunit2 for LINUX environment
        if: ${{ matrix.envOS == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install -y shunit2

      - name: Run the test folder with the shunit2 framework
        run: ./tests/test.sh $pathToFolder $owner $token $expectedPackageName
